apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: continuum-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: continuum-tls-staging
      hosts:
        - continuum-staging.example.com
  rules:
    - host: continuum-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: continuum-api
                port:
                  name: http
